language: python
python:
  - "3.6"     
  - "3.7"
  - "3.8"
# command to run tests
before_install:
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
  - pip install -U pip
  - python setup.py install
script:
  - python -m pytest --cov=Medeina
after_success:
  - codecov